unstable_features = true
edition = "2021"
max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
indent_style = "Block"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
fn_single_line = false
struct_field_align_threshold = 20
reorder_imports = true
trailing_comma = "Vertical"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
control_brace_style = "AlwaysSameLine"
format_strings = true
imports_indent = "Block"
imports_granularity = "Crate"
